# Docker

# Build and push an image to Docker hub
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  DockerHubConnection: '7d61feb1-ec77-488e-9ee3-f5d3f26e065b'
  imageRepository: 'kwetter'
  containerRegistry: 'sebananas/kwetter'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Buildtest
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'sebananas/kwetter'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
