# Docker

# Build and push an image to Docker hub
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  DockerHubConnection: '7d61feb1-ec77-488e-9ee3-f5d3f26e065b'
  imageRepository: 'kwetter'
  containerRegistry: 'sebananas/kwetter'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Main
  displayName: Setup build analyse and deploy
  pool:
    vmImage: windows-latest  
  jobs:
  - job: Setup
    displayName: Setup build analyse and deploy
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'NodeJS/'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloudFrontend'
        organization: 'kwetter-fontys'
        scannerMode: 'CLI'
        configMode: 'file'
        
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

- stage: Deploy
  pool:
    vmImage: $(vmImageName)
  jobs:
  - job: Deploy
    displayName: Deploy to docker
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'sebananas/kwetter'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
