# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a243c98a-6be4-41b6-b587-15ece1390e3a'
  imageRepository: 'kwetter'
  containerRegistry: 'kwetterregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  dockerHub: 'kwetterregistry'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          $(dockerHub)
        repository: $(imageName)
        command: push
        tags: |
          latest
          
